name: Deploy to Firebase Hosting on push

on:
  push:
    branches:
      - '**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      
      - name: Crear archivo .env
        run: |
          echo "VITE_FIREBASE_API_KEY=${{ secrets.VITE_FIREBASE_API_KEY }}" >> .env
          echo "VITE_FIREBASE_AUTH_DOMAIN=${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}" >> .env
          echo "VITE_FIREBASE_PROJECT_ID=${{ secrets.VITE_FIREBASE_PROJECT_ID }}" >> .env
          echo "VITE_FIREBASE_STORAGE_BUCKET=${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}" >> .env
          echo "VITE_FIREBASE_MESSAGING_SENDER_ID=${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}" >> .env
          echo "VITE_FIREBASE_APP_ID=${{ secrets.VITE_FIREBASE_APP_ID }}" >> .env
          echo "VITE_FIREBASE_MEASUREMENT_ID=${{ secrets.VITE_FIREBASE_MEASUREMENT_ID }}" >> .env
        shell: bash

      - name: Install Dependencies
        run: npm install

      - name: Build
        # Asegúrate de que las variables de entorno estén disponibles durante el proceso de build
        env:
          VITE_GROQ_API_KEY: ${{ secrets.VITE_GROQ }}  # Aquí asegúrate de que el nombre del secreto sea el correcto y esté definido en GitHub Secrets
        run: npm run build

      - name: Set Channel ID for Preview Deployments
        if: github.ref != 'refs/heads/main'
        run: echo "CHANNEL_ID=$(echo ${GITHUB_REF#refs/heads/} | sed 's/[^a-zA-Z0-9]/-/g')-preview" >> $GITHUB_ENV

      - name: Deploy to Firebase Hosting Live Channel
        if: github.ref == 'refs/heads/main'
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_SEGURIDADSALUD_60B15 }}'
          channelId: live
          projectId: seguridadsalud-60b15

      - name: Deploy to Firebase Hosting Preview Channel for Non-Main Branches
        if: github.ref != 'refs/heads/main'
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_SEGURIDADSALUD_60B15 }}'
          projectId: seguridadsalud-60b15
          channelId: ${{ env.CHANNEL_ID }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
